on: [push]

name: CI

env:
  RUSTFLAGS: "-Dwarnings"
  RUST_BACKTRACE: full

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: shellcheck ./scripts/*.sh
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo clippy --all-targets --all-features
  linux_unit_tests:
    needs: clippy
    name: Unit tests (Ubuntu)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo test --all-features
  linux_integ_debug:
    needs: [linux_unit_tests, shellcheck]
    name: Integration tests (Ubuntu, debug)
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: cargo build
      - run: ./scripts/integ-test.sh -p 8080
  linux_integ_release:
    needs: linux_integ_debug
    name: Integration tests (Ubuntu, release)
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: cargo build --release
      - run: ./scripts/integ-test.sh -p 8080 -r
  mac_unit_tests:
    needs: clippy
    name: Unit tests (macOS)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo test --all-features
  mac_integ_debug:
    needs: [mac_unit_tests, shellcheck]
    name: Integration tests (macOS, debug)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: brew install bash
      - run: cargo build
      - run: ./scripts/integ-test.sh -p 8080
  mac_integ_release:
    needs: mac_integ_debug
    name: Integration tests (macOS, release)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: brew install bash
      - run: cargo build --release
      - run: ./scripts/integ-test.sh -p 8080 -r
  windows_unit_tests:
    needs: clippy
    name: Unit tests (windows)
    runs-on: windows-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - run: cargo test --all-features
